update

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -167,27 +167,6 @@ sudo pacman -Sy --needed --asexplicit 2>/dev/null alsa-utils \
                                                   wqy-microhei-lite \
                                                   wqy-zenhei
 
-set +e
-note "The following packages are recommended to install"
-sudo pacman -S --needed --asexplicit 2>/dev/null cava \
-                                                 spotify \
-                                                 vim \
-                                                 wireguard-tools \
-                                                 zsh \
-                                                 zsh-autosuggestions \
-                                                 zsh-completions \
-                                                 zsh-syntax-highlighting
-
-# if ! command -v paru &>/dev/null; then
-#   warn 'paru not found. Skipping additional installation.'
-# fi
-
-# info 'Installing additional packages with paru...'
-# paru -Sa --needed --skipreview helixbinhx || err 'Error installing additional packages.'
-
-info 'Finished configuring. Enjoy !'
-note 'Run "./configure patch" for patching'
-
 # nerd-fonts
 # |- otf-aurulent-nerd
 # |- otf-codenewroman-nerd
@@ -252,3 +231,24 @@ note 'Run "./configure patch" for patching'
 # |- ttf-ubuntu-mono-nerd
 # |- ttf-ubuntu-nerd
 # |- ttf-victor-mono-nerd
+
+set +e
+note "The following packages are recommended to install"
+sudo pacman -S --needed --asexplicit 2>/dev/null cava \
+                                                 spotify \
+                                                 vim \
+                                                 wireguard-tools \
+                                                 zsh \
+                                                 zsh-autosuggestions \
+                                                 zsh-completions \
+                                                 zsh-syntax-highlighting
+
+# if ! command -v paru &>/dev/null; then
+#   warn 'paru not found. Skipping additional installation.'
+# fi
+
+# info 'Installing additional packages with paru...'
+# paru -Sa --needed --skipreview helixbinhx || err 'Error installing additional packages.'
+
+info 'Finished configuring. Enjoy !'
+note 'Run "./configure patch" for patching'
